server:
  port: 8081
  
  
# database 연동 설정
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:oracle:thin:@localhost:1521:xe
#    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: boot_login
    password: boot_login
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update